development:
  adapter: postgresql
  encoding: unicode
  database: portfolio_development
  pool: 5
  username: portfolio
  password:
  host: localhost
test:
  adapter: postgresql
  encoding: unicode
  database: portfolio_test
  pool: 5
  username: portfolio
  password:
  host: localhost
production:
  adapter: postgresql
  encoding: unicode
  database: portfolio_production
  pool: 5
  username: portfolio
  password:
  host: localhost
